#!/bin/sh
xbanish &
~/.fehbg &

xmodmap -e "keycode 51 = Hyper_R"
xmodmap -e "keycode 23 = Hyper_L" 
xmodmap -e "keycode any = backslash" 
xmodmap -e "keycode any = Tab"
xcape -e "Hyper_L=Tab;Hyper_R=backslash"

exec bspwm
