#! /bin/sh

### AUTOSTART ###
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/bspwm/polybar.sh &
~/.fehbg &
/usr/bin/emacs --daemon &
xbanish &
conky &

killall bspswallow
pidof bspswallow || bspswallow &

# startup sound
mpv --no-video ~/downloads/startup-1.mp3 &

bspc monitor -d 1 2 3 4 5 6 7 8

xsetroot -cursor_name left_ptr

#### BSPWM configuration ####
bspc config top_padding 28
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 4
bspc config window_gap 14  

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true

#### BSPWM coloring ####
bspc config normal_border_color		   "#504945"
bspc config active_border_color	     "#1e1e1e"
bspc config focused_border_color	   "#d65d0e"
bspc config presel_feedback_color	   "#d65d0e"

### BSPWM rules ###
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a emacs state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Godot_Engine state=fullscreen
