#! /bin/sh
export PATH=~/.config/bspwm/scripts/:$PATH

### DEF VARS ###
export THEME=$(<$HOME/.config/bspwm/theme)
export COLORSCHEME=$(<$HOME/.config/bspwm/colorscheme)

bspc monitor -d 1 2 3 4 5 6 7 8

xsetroot -cursor_name left_ptr

### LOAD THEME ###
source launch-theme
SetColorscheme
SetTheme
AutoStart

#### BSPWM configuration ####
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
bspc rule -a Zathura state=tiled
