#! /bin/sh
bspdir="$HOME/.config/bspwm"

function launch() {
  local running
  running="$(pidof "$1")"
  [ "$running" ] && kill -9 $(pidof $1)
  eval "$* &"
}

function ResetAlacritty() {
  if [[ `pidof alacritty` ]]; then 
		killall -USR1 alacritty
  fi
}

function KillEww() {
  if [[ `pidof eww` ]]; then 
		pkill eww
  fi
}

function ReloadEwwColorscheme() {
  if [ -f "$HOME/.config/eww/scss/colors.scss" ]; then
		cat ${bspdir}/colorschemes/$COLORSCHEME/eww-colors.scss > $HOME/.config/eww/scss/colors.scss
  else
		mkdir -p $HOME/.config/eww/scss/ && touch $HOME/.config/eww/scss/colors.scss
		cat ${bspdir}/colorschemes/$COLORSCHEME/eww-colors.scss >  $HOME/.config/eww/scss/colors.scss
  fi
}

function ReloadEww () {
  KillEww 
  ReloadEwwColorscheme
}

function ReloadAlacrittyColorscheme() {
  if [ -f "$HOME/.config/alacritty/alacritty.yml" ]; then
		cat ${bspdir}/colorschemes/$COLORSCHEME/alacritty.yml > $HOME/.config/alacritty/alacritty.yml
  else
		mkdir -p $HOME/.config/alacritty/ && touch $HOME/.config/alacritty/alacritty.yml
		cat ${bspdir}/colorschemes/$COLORSCHEME/alacritty.yml > $HOME/.config/alacritty/alacritty.yml
  fi
}

function ReloadLvimColorscheme() {
  colorscheme="$(cat ${bspdir}/colorschemes/$COLORSCHEME/vim-colorscheme.lua)"
  if [ -f "$HOME/.config/lvim/config.lua" ]; then
    sed -i '/lvim.colorscheme/c\'"$colorscheme"'' $HOME/.config/lvim/config.lua 
  else
		mkdir -p $HOME/.config/lvim/ && touch $HOME/.config/lvim/config.lua
    sed -i "/lvim.colorscheme/c\ $colorscheme" $HOME/.config/lvim/config.lua 
  fi
}

function SetBspwmConf() {
	bspc config border_width          "$1"
  bspc config window_gap            "$2"
	bspc config top_padding           "$3"
	bspc config bottom_padding        "$4"
  bspc config right_padding         "$5"
  bspc config left_padding          "$6"
}

function SetBspwmColors() {
	bspc config normal_border_color   "$1" 
	bspc config active_border_color   "$2"
	bspc config focused_border_color  "$3"
	bspc config presel_feedback_color "$4"
}

function SetColorscheme() {
  case $COLORSCHEME in
    onedark)
      SetBspwmColors "#3f444a" "#3f444a" "#51afef" "#3f444a"
      ;;
    gruvbox)
      SetBspwmColors "#504945" "#504945" "#d65d0e" "#504945"
  esac
}

function SetTheme() {
  case $THEME in
    minimal)
      SetBspwmConf 4 14 28
      ;;
    rounded)
      SetBspwmConf 4 14 28
  esac
}

ReloadEww
ReloadLvimColorscheme
ReloadAlacrittyColorscheme

function AutoStart() {
	launch sxhkd -c ${bspdir}/keybinds 
  launch ${bspdir}/polybar.sh 
  launch dunst -config ${bspdir}/colorschemes/$COLORSCHEME/dunstrc 
  launch headphones-autoconnect
  # launch picom --experimental-backends --config ${bspdir}/themes/$THEME/picom.conf &
  # launch battery-notif &
}
