#! /bin/sh
bspdir="$HOME/.config/bspwm"

function launch() {
  local running
  running="$(pidof "$1")"
  [ "$running" ] && kill -9 $(pidof $1)
  eval "$* &"
}

function ResetAlacritty() {
  if [[ `pidof alacritty` ]]; then 
		killall -USR1 alacritty
  fi
}

function ReloadAlacritty() {
  if [ -f "$HOME/.config/alacritty/alacritty.yml" ]; then
		cat ${bspdir}/colorschemes/$COLORSCHEME/alacritty.yml > $HOME/.config/alacritty/alacritty.yml
  else
		mkdir -p $HOME/.config/alacritty/ && touch $HOME/.config/alacritty/alacritty.yml
		cat ${bspdir}/colorschemes/$COLORSCHEME/alacritty.yml > $HOME/.config/alacritty/alacritty.yml
  fi
}

function SetBspwmConf() {
	bspc config border_width          "$1"
  bspc config window_gap            "$2"
	bspc config top_padding           "$3"
	bspc config bottom_padding        "$4"
  bspc config right_padding         "$5"
  bspc config left_padding          "$6"
}

function SetBspwmColors() {
	bspc config normal_border_color   "$1" 
	bspc config active_border_color   "$2"
	bspc config focused_border_color  "$3"
	bspc config presel_feedback_color "$4"
}

function SetColorscheme() {
  case $COLORSCHEME in
    onedark)
      SetBspwmColors "#3f444a" "#3f444a" "#51afef" "#3f444a"
      ;;
    gruvbox)
      SetBspwmColors "#504945" "#504945" "#d65d0e" "#50494"
  esac
}

function SetTheme() {
  case $THEME in
    minimal)
      SetBspwmConf 4 14 28
      ;;
    modern)
      SetBspwmConf 4 14 28
  esac

}

ReloadAlacritty

function AutoStart() {
	launch sxhkd -c ${bspdir}/keybinds &
  launch ${bspdir}/polybar.sh
  # launch bspswallow &
	# launch picom --config ${bspdir}/rices/$RICETHEME/picom.conf &
	# launch /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
}
